"use client";

import React, { useState } from "react";
import RiskIndicator from "@/demoComponents/result/RiskIndicator";
import FeatureCards from "@/demoComponents/result/FeatureCards";
import SectorGrowth from "@/demoComponents/result/SectorGrowth";
import ImportantEvents from "@/demoComponents/result/ImportantEvents";
import MarketAnalysis from "@/demoComponents/result/MarketAnalysis";
import QuickSend from "@/components/chatbot/QuickSend";

const result = {
  sector_with_most_growth_potential: "health_care",
  sector_with_least_growth_potential: "consumer_discretionary",
  growing_sectors: [
    "communication_services",
    "consumer_staples",
    "energy",
    "financials",
    "health_care",
    "industrials",
    "information_technology",
    "real_estate",
    "utilities",
  ],
  declining_sectors: ["consumer_discretionary", "materials"],
  top_5_events: [
    {
      event:
        "Tiny Maldives Bans Israelis From Vacation Paradise: Nearly 100 Percent Muslim Country\u2019s President Lashes Out at \u2018Atrocities\u2019 and \u2018Genocide\u2019 | The New York Sun",
      impact: 2.3374,
    },
    {
      event: "PM: US drug probe may be entrapment | The Tribune",
      impact: 4.8156,
    },
    {
      event:
        "City of Vandalia approves two development agreements at Monday Special Meeting | Vandalia Radio",
      impact: 3.0164,
    },
    {
      event:
        "Democrat Cyndi Munson announces bid for Oklahoma governor against growing field of Republicans",
      impact: 3.9592,
    },
    {
      event: "Malta Airport hails introduction of new routes ahead of the summer",
      impact: 6.72,
    },
  ],
  all_predictions: {
    communication_services: 0.6649,
    consumer_discretionary: -1.1284,
    consumer_staples: 0.2536,
    energy: 0.1755,
    financials: 0.7839,
    health_care: 1.1624,
    industrials: 0.2625,
    information_technology: 0.2694,
    materials: -0.6044,
    real_estate: 0.667,
    utilities: 0.0552,
  },
};

const ResultDisplay: React.FC = () => {
  const [activeFeature, setActiveFeature] = useState<number | null>(null);
  const [message, setMessage] = useState("");

  // Sends a messsage to the chatbot
  const handleSendMessage = () => {
    console.log("Message sent:", message);
    setMessage("");
  };

  if (!result) {
    return (
      <div className='min-h-screen flex items-center justify-center bg-gray-100 dark:bg-gray-900 p-4'>
        <div className='bg-white dark:bg-gray-800 backdrop-blur-md rounded-2xl p-8 shadow-xl'>
          <h2 className='text-xl font-bold text-white'>
            No result available yet. Please submit your portfolio first.
          </h2>
        </div>
      </div>
    );
  }

  const riskLevel =
    Object.values(result.all_predictions as Record<string, number>).filter((val) => val < 0)
      .length > 3
      ? "High"
      : "Low";

  return (
    <div className='min-h-screen bg-gray-100 dark:bg-gray-900 p-4 md:p-8'>
      <div className='max-w-6xl mx-auto'>
        <RiskIndicator riskLevel={riskLevel} />
        {activeFeature === null && <FeatureCards setActiveFeature={setActiveFeature} />}

        {/* Predictions for each sector */}
        {activeFeature === 1 && <SectorGrowth setActiveFeature={setActiveFeature} />}

        {/* Top events and how they impact the portfolio */}
        {activeFeature === 2 && <ImportantEvents setActiveFeature={setActiveFeature} />}

        {/* All information generated by the backend */}
        {activeFeature === 3 && <MarketAnalysis setActiveFeature={setActiveFeature} />}

        {/* Quick form to talk to the chatbot */}
        <QuickSend onSend={handleSendMessage} />

        {/* Disclaimer that responses are ai-generated */}
        <div className='mt-8 p-4 bg-gray-800 rounded-lg shadow-md'>
          <p className='text-yellow-400 text-center font-medium'>
            Heads up! This content was AI-generated—double-check anything important just to be sure.
          </p>
        </div>
      </div>
    </div>
  );
};

export default ResultDisplay;
